backend:
  name: github
  repo: meghnahumanity/meghnahumanity.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
    - name: "post"
    label: "পোস্ট"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "শিরোনাম", name: "title", widget: "string"}
            - {label: "তারিখ", name: "date", widget: "datetime"}
            - {label: "ছবি", name: "thumbnail", widget: "image", required: false}
            - {label: "মূল লেখা", name: "body", widget: "markdown"}
